# Generated by Django 3.0.5 on 2021-04-16 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinventory',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientinventory',
            name='item_availability',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
